-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/webdav.saves.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_webdav_saves (
  wds_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  wds_user_id INTEGER NOT NULL, wds_filename BLOB NOT NULL,
  wds_path BLOB NOT NULL, wds_ts INTEGER NOT NULL
);
