#!/bin/bash
# ============================================================
# BlueSpice HDP — First-boot Setup Script
# Runs INSIDE the mediawiki (PHP-FPM) container.
#
# Does three things:
#   1. Resolves the Composer problem (two private hallowelt packages
#      whose full source is already committed in extensions/)
#   2. Installs MediaWiki with MariaDB backend
#   3. Runs update.php to create all extension tables
#
# Usage:
#   docker compose exec mediawiki bash /setup.sh
# ============================================================
set -euo pipefail

MW=/var/www/html/w
cd "$MW"

# ─── Load secrets from Infisical ────────────────────────────────────
if [ -f /infisical-loader.sh ]; then
    source /infisical-loader.sh
fi

# ─── Environment ───────────────────────────────────────────────────
DB_HOST="${DB_HOST:-mariadb}"
DB_NAME="${MW_DB_NAME:-bluespice}"
DB_USER="${MW_DB_USER:-bluespice}"
DB_PASS="${MW_DB_PASS:-${HDP_DB_PASSWORD}}"
ADMIN_PASS="${WIKI_ADMIN_PASS:-${HDP_ADMIN_PASSWORD}}"
SERVER="${MW_SERVER:-http://localhost:8080}"
LANG="${MW_LANG:-de}"
SITENAME="${MW_SITENAME:-BlueSpice HDP}"

echo "============================================"
echo " BlueSpice HDP Setup"
echo "============================================"
echo " DB:   ${DB_USER}@${DB_HOST}/${DB_NAME}"
echo " URL:  ${SERVER}/w"
echo " Lang: ${LANG}"
echo "============================================"
echo ""

# ─── Step 0: Wait for MariaDB ──────────────────────────────────────
echo "[0/4] Waiting for MariaDB at ${DB_HOST}..."
max_wait=120
waited=0
while ! mariadb -h "${DB_HOST}" -u "${DB_USER}" -p"${DB_PASS}" -e "SELECT 1" "${DB_NAME}" &>/dev/null; do
    if [ "$waited" -ge "$max_wait" ]; then
        echo "ERROR: MariaDB not reachable after ${max_wait}s"
        exit 1
    fi
    sleep 2
    waited=$((waited + 2))
    printf "."
done
echo " OK (${waited}s)"

# ─── Step 1: Fix Composer ─────────────────────────────────────────
# ─── Pre-step: Install python3 for SyntaxHighlight (Pygments) ──────
# The Wikimedia dev image doesn't include python3, but BlueSpice's
# SyntaxHighlight_GeSHi extension shells out to Pygments for code
# block rendering. Without it, every page with a code block spams
# PHP notices and renders as plain <pre>.
if ! command -v python3 &>/dev/null; then
    echo "Installing python3 + pygments for syntax highlighting..."
    # mirrors.wikimedia.org is unresolvable outside Wikimedia's own network —
    # the base image's default Debian mirror. Point at deb.debian.org instead
    # so apt-get update can actually populate a package index.
    sed -i 's#mirrors\.wikimedia\.org#deb.debian.org#g' /etc/apt/sources.list
    # The base image ships /etc/apt/sources.list.d/php.list pointing at
    # packages.sury.org, whose signing key has expired:
    #   E: The repository 'https://packages.sury.org/php bookworm InRelease'
    #      is not signed.  (EXPKEYSIG B188E2B695BD4743)
    # apt-get update then exits non-zero, which the `|| true` below swallows,
    # so the whole run looks like it failed even when the index is fine. We
    # install nothing from sury — python3 and python3-pygments come from Debian
    # main — so drop the source rather than chase a fresh key.
    rm -f /etc/apt/sources.list.d/php.list /etc/apt/sources.list.d/sury*.list
    apt-get update -qq || true
    apt-get install -y -qq --no-install-recommends python3 python3-pygments >/dev/null 2>&1
    echo "  Done."
fi

# Two packages (hallowelt/chatbot, mediawiki/page-header) point to
# gitlab.hallowelt.com (private, no auth). Their full source is already
# committed in extensions/ChatBot/ and extensions/PageHeader/.
# We: disable the merge-plugin (composer.local.json → {}),
#     strip the two packages from composer.lock,
#     rm vendor/, reinstall, restore, dump-autoload.

if [ ! -f vendor/autoload.php ] || [ ! -f vendor/autoload_real.php ]; then
    echo ""
    echo "[1/4] Resolving Composer dependencies..."

    # Force HTTPS-only GitHub access. A composer.lock that pins a package's
    # VCS source to the SSH form (git@github.com:...) breaks fresh containers,
    # which have no SSH client or keys: composer fails with either "cannot run
    # ssh: No such file or directory" or an internal TypeError in
    # Git::runCommand(). The github-protocols config alone does not help — it
    # does not rewrite an already-pinned SSH URL.
    #
    # The committed composer.lock now stores https:// sources, so this sed is
    # a no-op on a clean checkout. It stays as a safety net for locks
    # regenerated by a developer whose git rewrites github.com to SSH.
    sed -i 's#git@github\.com:#https://github.com/#g' composer.lock
    composer config --global github-protocols https

    # Backup and neutralize composer.local.json (disables MWStake merge-plugin
    # which declares the VCS repos for the private packages)
    if [ -f composer.local.json ]; then
        cp composer.local.json composer.local.json.bak
    fi
    echo '{}' > composer.local.json

    # Strip the two private packages from composer.lock using jq
    if command -v jq &>/dev/null; then
        jq 'del(.packages[] | select(.name == "hallowelt/chatbot" or .name == "mediawiki/page-header"))' \
            composer.lock > composer.lock.tmp
        mv composer.lock.tmp composer.lock
    else
        # Fallback: python3
        python3 -c "
import json, sys
with open('composer.lock') as f:
    lock = json.load(f)
lock['packages'] = [p for p in lock.get('packages', [])
                    if p.get('name') not in ('hallowelt/chatbot', 'mediawiki/page-header')]
with open('composer.lock', 'w') as f:
    json.dump(lock, f, indent=4)
"
    fi

    # Remove vendor/ and reinstall (ignores the stripped packages)
    rm -rf vendor/
    git config --global --add safe.directory "${MW}" || true
    git config --global --add safe.directory '*' || true
    composer install --no-dev --no-interaction --prefer-dist --ignore-platform-reqs

    # Restore composer.local.json
    if [ -f composer.local.json.bak ]; then
        mv composer.local.json.bak composer.local.json
    fi

    # Regenerate autoloader — picks up extension namespaces from
    # extensions/*/composer.json via the merge-plugin
    composer dump-autoload --no-dev --ignore-platform-reqs

    echo "[1/4] Composer dependencies resolved."
else
    echo "[1/4] Vendor directory already present, skipping composer."
fi

# ─── Post-composer: Re-apply SSL patch to ExtendedSearch Backend.php ──
# Composer installs bluespice/extendedsearch as a dist package, which
# overwrites our local patch to Backend.php. Re-apply it here so the
# SSL verification fix survives every fresh install.
ES_BACKEND="$MW/extensions/BlueSpiceExtendedSearch/src/Backend.php"
if [ -f "$ES_BACKEND" ] && ! grep -q 'setSSLVerification' "$ES_BACKEND"; then
    sed -i '/\$clientBuilder->setRetries( 2 );/a\
\t\t\t// HDP: disable SSL verification for self-signed OpenSearch certs\
\t\t\t\$clientBuilder->setSSLVerification( false );' "$ES_BACKEND"
    echo "  Re-applied SSL patch to ExtendedSearch Backend.php"
fi

# ─── Post-composer: Re-apply $searchCnt patch to SearchCenter.js ─────
# Same clobbering problem as Backend.php above, different file. Upstream
# extendedsearch 5.1.4 fires the 'bs.extendedsearch.searchcenter.getResults'
# hook with $searchCnt but never declares it, so a completed search throws
# "ReferenceError: $searchCnt is not defined" out of the .done() handler,
# before removeLoading() and result rendering run. Symptom: the Search
# Center spins its progress bar forever even though the API returned
# results. Bind it to the results container, which is what a hook observer
# would expect.
ES_SEARCHCENTER="$MW/extensions/BlueSpiceExtendedSearch/resources/ext.blueSpiceExtendedSearch.SearchCenter.js"
if [ -f "$ES_SEARCHCENTER" ] && ! grep -q 'const \$searchCnt' "$ES_SEARCHCENTER"; then
    sed -i "/const \$altSearchCnt = \$( '#bs-es-alt-search' );/a\\
\\t\\t// HDP: upstream fires the getResults hook with an undeclared \$searchCnt\\
\\t\\tconst \$searchCnt = \$resultCnt;" "$ES_SEARCHCENTER"
    echo "  Re-applied \$searchCnt patch to ExtendedSearch SearchCenter.js"
fi

# ─── Step 2: Install MediaWiki (MariaDB) ──────────────────────────
echo ""
if [ -f LocalSettings.php ]; then
    echo "[2/4] LocalSettings.php exists — skipping install."
else
    echo "[2/4] Installing MediaWiki with MariaDB..."

    # install.php is a standalone script — call it directly, NOT via run.php
    # (run.php prepends maintenance/ and would look for maintenance/maintenance/install.php)
    # NOTE: Do NOT use --with-extensions: it auto-discovers Echo and writes
    # wfLoadExtension('Echo') into LocalSettings.php, which then conflicts with
    # the BlueSpice shim in settings.d/030-BlueSpiceFreeDistribution.php that
    # loads Echo from a different path ("loaded twice" fatal).
    php maintenance/install.php \
        --dbtype mysql \
        --dbserver "${DB_HOST}" \
        --dbuser "${DB_USER}" \
        --dbpass "${DB_PASS}" \
        --dbname "${DB_NAME}" \
        --installdbuser "${DB_USER}" \
        --installdbpass "${DB_PASS}" \
        --server "${SERVER}" \
        --scriptpath /w \
        --lang "${LANG}" \
        --pass "${ADMIN_PASS}" \
        "${SITENAME}" Admin

    # The installer generates a clean LocalSettings.php that auto-detects
    # all extensions in extensions/ and writes wfLoadExtension() calls for
    # each one. But BlueSpice uses settings.d/*.php to load extensions in a
    # specific order with custom configuration. Having both causes "loaded
    # twice" fatals (e.g. Echo is loaded natively AND via a BlueSpice shim).
    # Solution: strip all auto-generated wfLoadExtension lines, then append
    # the BlueSpice settings loader.

    # Remove all auto-generated wfLoadExtension lines
    sed -i '/^wfLoadExtension(/d' LocalSettings.php

    # Append the BlueSpice settings loader (loads all settings.d/*.php —
    # this activates ~130 extensions in the correct order with config).
    if ! grep -q "LocalSettings.BlueSpice.php" LocalSettings.php; then
        echo "" >> LocalSettings.php
        echo "// BlueSpice extension settings" >> LocalSettings.php
        echo "require_once \"\$IP/LocalSettings.BlueSpice.php\";" >> LocalSettings.php
    fi

    # Suppress verbose deprecation notices in HTTP output
    # (Wikimedia dev image sets display_errors=1 via DevelopmentSettings.php)
    if ! grep -q "display_errors" LocalSettings.php; then
        echo "" >> LocalSettings.php
        echo "// Suppress dev-mode error display" >> LocalSettings.php
        echo "ini_set( 'display_errors', '0' );" >> LocalSettings.php
    fi

    echo "[2/4] MediaWiki installed."
fi

# ─── Pre-step 3: Prepare writable data dirs ───────────────────────
# SMW's setup writes .smw.json under BlueSpiceFoundation/data during
# update.php. If the directory isn't writable by the PHP user, update.php
# emits a scary "ERROR: .smw.json is not writable" line even though the
# overall run still succeeds. Preparing the dir + file (and fixing perms)
# BEFORE step [3/4] avoids the error entirely.
mkdir -p extensions/BlueSpiceFoundation/data extensions/SemanticMediaWiki/data 2>/dev/null || true
touch extensions/BlueSpiceFoundation/data/.smw.json 2>/dev/null || true

# The Wikimedia dev image's ResourceLoader expects tests/qunit/QUnitTestResources.php
# (normally generated by Wikimedia dev tooling, not part of the HDP repo).
# Without it, every page load fatals with "Unsupported operand types: bool + array".
mkdir -p tests/qunit
if [ ! -f tests/qunit/QUnitTestResources.php ]; then
    echo '<?php return [];' > tests/qunit/QUnitTestResources.php
fi

# Fix ownership for FPM workers (www-data) BEFORE update.php runs, so
# SMW's setup can write .smw.json on the first pass.
chown -R www-data:www-data cache/ images/ tests/ \
    extensions/BlueSpiceFoundation/data extensions/SemanticMediaWiki/data 2>/dev/null || true

# ─── Step 3: Run update.php (creates extension tables) ────────────
echo ""
echo "[3/4] Running update.php (creates BlueSpice extension tables)..."
php maintenance/run.php update.php --quick --skip-config-validation
echo "[3/4] update.php complete."

# ─── Step 4: Final permissions sweep ──────────────────────────────
echo ""
echo "[4/4] Final permissions sweep..."

# Re-apply ownership in case update.php created new files as root
chown -R www-data:www-data cache/ images/ tests/ \
    extensions/BlueSpiceFoundation/data extensions/SemanticMediaWiki/data 2>/dev/null || true

echo "[4/4] Done."

# ─── Step 4b: Populate main page (first install only) ─────────────
# Replace the generic upstream BlueSpice welcome boilerplate with usage
# instructions + an auto-updating content overview (DynamicPageList-driven
# "recently edited" list). Runs only once, guarded by a marker file, so
# later manual edits by wiki admins are never overwritten on container
# restart.
if [ -f /hauptseite.wiki ] && [ ! -f cache/.hauptseite-populated ]; then
    echo ""
    echo "[4/4] Populating main page with usage instructions..."
    php maintenance/run.php edit.php \
        --user Admin \
        --summary "Initial setup: populate main page with usage instructions" \
        Hauptseite < /hauptseite.wiki \
        && touch cache/.hauptseite-populated \
        || echo "  WARNING: main page population failed (non-fatal, continuing)"
fi

# ─── Step 4c: Populate Chatbot-FAQ (first install only) ───────────
# Ships a German FAQ page explaining how the chatbot works, what it
# can/can't answer, source attribution, and privacy. Guarded by a
# marker file so admin edits are never overwritten on restart.
if [ -f /chatbot-faq.wiki ] && [ ! -f cache/.chatbot-faq-populated ]; then
    echo ""
    echo "[4/4] Populating Chatbot-FAQ page..."
    php maintenance/run.php edit.php \
        --user Admin \
        --summary "Initial setup: populate Chatbot-FAQ page" \
        Chatbot-FAQ < /chatbot-faq.wiki \
        && touch cache/.chatbot-faq-populated \
        || echo "  WARNING: Chatbot-FAQ population failed (non-fatal, continuing)"
fi

# ─── Step 4c2: Populate Site: legal placeholder pages (first install) ─
# BlueSpice shows a yellow warning banner on every page until
# Site:Nutzungsbedingungen and Site:Datenschutz exist. These are
# minimal placeholders — the admin should customize them.
if [ ! -f cache/.site-pages-populated ]; then
    echo ""
    echo "[4/4] Populating Site: legal placeholder pages..."
    for page_file in \
        "Site:Nutzungsbedingungen|/site-nutzungsbedingungen.wiki" \
        "Site:Datenschutz|/site-datenschutz.wiki"; do
        page="${page_file%%|*}"
        file="${page_file##*|}"
        if [ -f "$file" ]; then
            echo "  -> ${page}"
            php maintenance/run.php edit.php \
                --user Admin \
                --summary "Initial setup: populate legal placeholder page" \
                "$page" < "$file" \
                || echo "  WARNING: population of ${page} failed (non-fatal, continuing)"
        fi
    done
    touch cache/.site-pages-populated
fi

# ─── Step 4d: Populate codewiki Help-namespace docs (first install only) ─
# Ships the docs/wiki/*.md tree (converted to wikitext by
# scripts/convert-docs.sh, checked into docker/mediawiki/wiki-docs/) into
# the Help namespace so the main-page links to Help:Technische_Dokumentation,
# Help:Architektur, Help:Erste_Schritte, Help:Modul/*, Help:Diagramme/*
# and Help:Inhaltsverzeichnis are no longer red. Uses '__' in filenames as
# a stand-in for '/' in subpage names (see convert-docs.sh).
# Guarded by a marker file so admin edits are never overwritten on restart.
if [ -d /wiki-docs ] && [ ! -f cache/.wiki-docs-populated ]; then
    echo ""
    echo "[4/4] Populating codewiki Help pages..."
    for f in /wiki-docs/*.wiki; do
        [ -f "$f" ] || continue
        base="$(basename "$f" .wiki)"
        # Turn 'Help:Modul__Ingestion' into 'Help:Modul/Ingestion'.
        page="${base//__//}"
        echo "  -> ${page}"
        php maintenance/run.php edit.php \
            --user Admin \
            --summary "Initial setup: populate codewiki-generated Help page" \
            "${page}" < "$f" \
            || echo "  WARNING: population of ${page} failed (non-fatal, continuing)"
    done
    touch cache/.wiki-docs-populated
fi

# ─── Step 4e: Initialize ExtendedSearch index (first install only) ──
# BlueSpice's ExtendedSearch needs the OpenSearch backend initialized and
# the initial index built. Without this, wiki search returns zero results.
# Guarded by a marker file so re-runs don't rebuild from scratch.
if [ ! -f cache/.extendedsearch-initialized ]; then
    echo ""
    echo "[4/4] Initializing ExtendedSearch index..."
    echo "  This queues background indexing jobs and may take a few minutes..."
    ES_MAINT="$MW/extensions/BlueSpiceExtendedSearch/maintenance"
    php maintenance/run.php "$ES_MAINT/initBackends.php" --quick 2>&1 \
        || echo "  WARNING: initBackends failed (may already be initialized)"
    php maintenance/run.php "$ES_MAINT/rebuildIndex.php" --quick 2>/dev/null \
        || echo "  WARNING: rebuildIndex failed (non-fatal, jobs may still be processing)"
    touch cache/.extendedsearch-initialized
    echo "  ExtendedSearch initialized. Background jobs will finish indexing."
fi

echo ""
echo "============================================"
echo " ✓ Setup complete!"
echo "============================================"
echo ""
echo " Wiki:    ${SERVER}/w/"
echo " Admin:   ${SERVER}/w/index.php/Special:UserLogin"
echo " User:    Admin"
echo ""
echo "============================================"
