-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/webdav.saves.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_webdav_saves (
  wds_id INT AUTO_INCREMENT NOT NULL,
  wds_user_id INT NOT NULL,
  wds_filename VARBINARY(255) NOT NULL,
  wds_path VARBINARY(255) NOT NULL,
  wds_ts INT NOT NULL,
  PRIMARY KEY(wds_id)
) /*$wgDBTableOptions*/;
